authentication/urls.py
from django.urls import path
from .views import login,logout_view


app_name = 'authentication'
urlpatterns = [
    path('login/',login,name='login-form'),
    path('logout/',logout_view,name='logout')
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect


urlpatterns = [
    path('', lambda request: redirect('/auth/login/')),
    path('admin/', admin.site.urls),
    path('auth/',include("authentication.urls")),
    path('dashboard/',include("dashboard.urls")),
    path('project/',include("project.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from .views import main,admin_tambah_personel,user_notification,admin_notifikasi,teams,edit_user


app_name = 'dashboard'
urlpatterns = [
    path('',main,name='main'),
    path('notifikasi/',user_notification,name='user-notification'),
    path('admin/tambah-personel/',admin_tambah_personel,name='tambah-personel'),
    path('admin/notifikasi',admin_notifikasi,name='admin-notification'),
    path('teams/',teams,name='teams'),
    path('edit-user/',edit_user,name='edit-user')
]

project/urls.py
from django.urls import path
from .views import projects


app_name = 'project'
urlpatterns = [
    path('',projects,name='projects'),
]

dashboard/models.py
from django.db import models
from authentication.models import CustomUser
from datetime import date

# Create your models here.
class InformasiKaryawan(models.Model):

    STATUS = (
        ('Accepted','Accepted'),
        ('Need Revision','Need Revision'),
        ('Pending','Pending')
    )

    JABATAN = (
        ('Partner','Partner'),
        ('Senior Manager','Senior Manager'),
        ('Manager','Manager'),
        ('Assistant Manager','Assistant Manager'),
        ('Senior Specialist','Senior Specialist'),
        ('Specialist','Specialist'),
        ('Admin','Admin')
    )

    STATUS_SERTIFIKASI = (
        ('A','A'),
        ('B','B'),
        ('C','C'),
        ('Bukan Konsultan Pajak','Bukan Konsultan Pajak')
    )

    STATUS_KUASA_HUKUM = (
        ('Ya','Ya'),
        ('Bukan Kuasa Hukum','Bukan Kuasa Hukum')
    )
    nama = models.CharField(max_length=150,unique=True)
    jabatan = models.CharField(choices=JABATAN,max_length=50)
    status_sertifikasi = models.CharField(choices=STATUS_SERTIFIKASI,max_length=50,null=True)
    status_kuasa_hukum = models.CharField(choices=STATUS_KUASA_HUKUM,max_length=50,null=True)
    pesan = models.TextField(default=None,null=True,blank=True)
    izin_berlaku_attorney = models.DateField(default=None,null=True,blank=True)
    izin_berlaku_konsultan = models.DateField(default=None,null=True,blank=True)
    status = models.CharField(choices=STATUS,default="Pending",max_length=50)

    def __str__(self):
        return self.nama
    
    @property
    def formatted_izin_berlaku_konsultan(self):
        if self.izin_berlaku_konsultan:
            return self.izin_berlaku_konsultan
        return "-"
    
    @property
    def formatted_izin_berlaku_attorney(self):
        if self.izin_berlaku_attorney:
            return self.izin_berlaku_attorney
        return "-"

    @property
    def days_until_izin_berlaku_konsultan(self):
        if self.izin_berlaku_konsultan:
            today = date.today()
            delta = self.izin_berlaku_konsultan - today
            return delta.days
        return None
    
    @property
    def days_until_izin_berlaku_attorney(self):
        if self.izin_berlaku_attorney:
            today = date.today()
            delta = self.izin_berlaku_attorney - today
            return delta.days
        return None

class Notifications(models.Model):

    # Informasi Personel --> Update (Nama, izin berlaku , dan status only) untuk User 

    NOTIFICATION_TYPE = (
        ('Karyawan Baru','Karyawan Baru'),
        ('Karyawan Keluar','Karyawan Keluar'),
        ('Jabatan','Jabatan'),
        ('Informasi Personal','Informasi Personal'),
        ('Projek','Projek')
    )

    STATUS = (
        ('Accepted','Accepted'),
        ('Declined','Declined'),
        ('Draft','Draft'),
        ('Request for update','Request for update')
    )

    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    informasi_karyawan = models.ForeignKey(InformasiKaryawan,on_delete=models.CASCADE)
    notification_type = models.CharField(choices=NOTIFICATION_TYPE,max_length=50)
    status = models.CharField(choices=STATUS,max_length=50,default='Draft')
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.informasi_karyawan.nama
    
class AdminNotifications(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True)
    informasi_karyawan = models.ForeignKey(InformasiKaryawan,on_delete=models.CASCADE)
    pesan = models.TextField()

    def __str__(self):
        return self.pesan

dashboard/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import Case,When
from .models import InformasiKaryawan,Notifications,AdminNotifications
from authentication.models import CustomUser
from datetime import datetime
from .xlsx_utils import import_karyawan_from_xlsx
# Create your views here.


@login_required(login_url='authentication:login-form')
def main(request):
    try:
        notifikasi_personal = Notifications.objects.get(user=request.user.id,notification_type="Informasi Personal")
        context = {
            'notifikasi_personal' : notifikasi_personal,
        }
    except Notifications.DoesNotExist:
        context = {
            'detail' : "Saat ini tidak ada notifikasi yang masuk"
        }

    if request.method == "POST":
        id = request.POST.get("personalUpdateId")
        informasi_karyawan = InformasiKaryawan.objects.get(id=id)
        status = request.POST.get("status")
        pesan = request.POST.get("update_reason")
        
        if status == "Accepted":
            informasi_karyawan.status = "Accepted"
            informasi_karyawan.save()
            notifikasi_personal.delete()
            success_message = "Update karyawan telah disetujui"
            messages.success(request, success_message)
            return redirect("dashboard:main")
        
        elif status == "Declined":
            informasi_karyawan.status = "Need Revision"
            informasi_karyawan.pesan = pesan
            informasi_karyawan.save()
            notifikasi_personal.delete()
            success_message = "Update karyawan telah diberi feedback"
            messages.success(request, success_message)
            return redirect("dashboard:main")



    return render(request,"dashboard/base/main.html",context)

@login_required(login_url='authentication:login-form')
def admin_tambah_personel(request):
    # Handle form tambah personel (Admin) lewat file
    if request.method == "POST" and "personel-file" in request.FILES:
        personel_file = request.FILES['personel-file']
        if personel_file:
            try:
                import_karyawan_from_xlsx(personel_file)
            except IntegrityError:
                messages.error(request,"Nama karyawan sudah ada")
                return redirect("dashboard:tambah-personel")

            success_message = "Personel karyawan berhasil ditambahkan melalui file"
            messages.success(request, success_message)
            return redirect("dashboard:tambah-personel")
        
    # Handle form tambah personel (Admin) satu - satu
    elif request.method == "POST":
        nama = request.POST.get('nama')
        jabatan = request.POST.get('jabatan')
        status_sertifikasi = request.POST.get('status_sertifikasi')
        status_kuasa_hukum = request.POST.get('status_kuasa_hukum')
        
        try:
            izin_berlaku_attorney = datetime.strptime(request.POST.get('izin_berlaku_attorney'), "%m/%d/%Y").strftime("%Y-%m-%d")
        except TypeError or ValueError:
            izin_berlaku_attorney = None
        try:
            izin_berlaku_konsultan = datetime.strptime(request.POST.get('izin_berlaku_konsultan'), "%m/%d/%Y").strftime("%Y-%m-%d")
        except TypeError or ValueError:
            izin_berlaku_konsultan = None

        informasi_karyawan = InformasiKaryawan(
            nama=nama,
            jabatan=jabatan,
            status_sertifikasi=status_sertifikasi,
            status_kuasa_hukum=status_kuasa_hukum,
            izin_berlaku_attorney=izin_berlaku_attorney,
            izin_berlaku_konsultan=izin_berlaku_konsultan
        )
        email = nama.replace(" ","").lower() + "@ddtc.dashboard"
        user = CustomUser(
            nama=nama,
            email=email,
            password="12345",
            role="user"
        )
        
        try:
            informasi_karyawan.save()
            user.save()
        except IntegrityError:
            messages.error(request,"Nama karyawan atau email sudah ada")
            return redirect("dashboard:tambah-personel")
        
        users_notified = CustomUser.objects.filter(role="Super User")
        
        for user_notified in users_notified:
            notifikasi = Notifications(
                user=user_notified,
                informasi_karyawan=informasi_karyawan,
                notification_type="Karyawan Baru"
            )
            notifikasi.save()

        success_message = "Personel karyawan berhasil ditambahkan (Menunggu approval)"
        messages.success(request, success_message)

        return render(request,"dashboard/admin/admin-tambah-personel.html")

    return render(request,"dashboard/admin/admin-tambah-personel.html")

def user_notification(request):
    notifikasi_karyawan_baru = Notifications.objects.filter(user=request.user.id,notification_type="Karyawan Baru")
    notifikasi_jabatan_baru = Notifications.objects.filter(user=request.user.id,notification_type="Jabatan")
    notifikasi_personal = Notifications.objects.filter(user=request.user.id,notification_type="Informasi Personal")
    
    context = {
        'notifikasi_karyawan_baru' : notifikasi_karyawan_baru,
        'notifikasi_jabatan_baru' : notifikasi_jabatan_baru,
        'notifikasi_personal' : notifikasi_personal,
        'detail' : "No income notification !"
    }

    if request.method == "POST":
        status = request.POST.get('status')
        nama = request.POST.get('nama')
        pesan = request.POST.get('update_reason')

        informasi_karyawan = InformasiKaryawan.objects.get(nama=nama)
        super_user = CustomUser.objects.filter(role="Super User")
        super_user_notifikasi = Notifications.objects.filter(user__in=super_user,informasi_karyawan=informasi_karyawan)
        user_admins = CustomUser.objects.filter(role="Admin")

        if status == "Accepted" :
            for notifikasi in super_user_notifikasi:
                notifikasi.delete()
            informasi_karyawan.status = "Accepted"
            informasi_karyawan.save()
            success_message = "Personel diterima"
            messages.success(request, success_message)
            return redirect('dashboard:user-notification')
        elif status == "Declined":
            for notifikasi in super_user_notifikasi:
                notifikasi.delete()
            informasi_karyawan.delete()
            success_message = "Personel ditolak"
            messages.success(request, success_message)
            return redirect('dashboard:user-notification')
        elif status == "Requested for update":
            for notifikasi in super_user_notifikasi:
                notifikasi.status = "Requested for update"
                notifikasi.save()
            for user_admin in user_admins:
                notifikasi_admin = AdminNotifications(user=user_admin,informasi_karyawan=informasi_karyawan,pesan=pesan)
                notifikasi_admin.save()
            success_message = "Meminta perubahan"
            messages.success(request, success_message)
            return redirect('dashboard:user-notification')
 
    return render(request,"dashboard/super_user/notifikasi.html",context)
    
def admin_notifikasi(request):
    notifikasi = AdminNotifications.objects.filter(user=request.user.id)
    
    context = {
        'notifikasi' : notifikasi,
        'detail' : "Saat ini tidak ada notifikasi yang masuk"
    }

    if request.method == "POST":
        id = request.POST.get('id')
        informasi_karyawan = InformasiKaryawan.objects.get(id=id)

        informasi_karyawan.nama = request.POST.get('nama')
        informasi_karyawan.jabatan = request.POST.get('jabatan')
        informasi_karyawan.status_sertifikasi = request.POST.get('status_sertifikasi')
        informasi_karyawan.status_kuasa_hukum = request.POST.get('status_kuasa_hukum')
        informasi_karyawan.izin_berlaku_attorney = datetime.strptime(request.POST.get('izin_berlaku_attorney'), "%m/%d/%Y").strftime("%Y-%m-%d")
        informasi_karyawan.izin_berlaku_konsultan = datetime.strptime(request.POST.get('izin_berlaku_konsultan'), "%m/%d/%Y").strftime("%Y-%m-%d")
        informasi_karyawan.status = "Pending"
        users_admin = CustomUser.objects.filter(role="Admin")

        try:
            informasi_karyawan.save()
        except IntegrityError:
            messages.error(request,"Nama karyawan sudah ada")
            return redirect("dashboard:admin-notification")
        
        for user_admin in users_admin:
            admin_notifikasi = AdminNotifications.objects.get(user=user_admin,informasi_karyawan=informasi_karyawan)
            admin_notifikasi.delete()
        success_message = "Personel karyawan berhasil diperbaiki (Menunggu approval)"
        messages.success(request, success_message)
        return redirect("dashboard:admin-notification")
        
    return render(request,"dashboard/admin/admin-notifikasi.html",context)

def teams(request):

    if request.method == "POST" and "jabatan" in request.POST:
        id = request.POST.get('id')
        jabatan = request.POST.get('jabatan')

        current_karyawan = InformasiKaryawan.objects.get(id=id)

        if current_karyawan.jabatan == jabatan:
            messages.error(request,"Jabatan tidak diubah")
            return redirect("dashboard:teams")
        

        current_karyawan.jabatan = jabatan
        current_karyawan.status = "Pending"
        current_karyawan.save()
        
        users_notified = CustomUser.objects.filter(role="Super User")
        
        for user_notified in users_notified:
            notifikasi = Notifications(
                user=user_notified,
                informasi_karyawan=current_karyawan,
                notification_type="Jabatan"
            )

dashboard/templates/dashboard/base/base-dashboard.html
<html>
{% load static %}

<head>
  <link rel="icon" href="{% static 'assets/DDTC-Logo.png' %}" type="image/x-icon">
  <title>{% block title %}{% endblock%}</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/datepicker.min.js"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            darkblue: {
              700: "#08294c",
              800: "#001529",
            },
            cream: "#FCF2E7",
            white: "#fff",
          },
        },
      },
    };
  </script>
  <style>
    .swal-text {
      text-align: center;
    }
  </style>
</head>

<body>
  <nav class="fixed top-0 z-50 w-full bg-darkblue-700 border-b border-gray-200 dark:bg-gray-800 dark:border-gray-700">
    <div class="px-3 py-3 lg:px-5 lg:pl-3">
      <div class="flex items-center justify-between">
        <div class="flex items-center justify-start">
          <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar"
            type="button"
            class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
            <span class="sr-only">Open sidebar</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg">
              <path clip-rule="evenodd" fill-rule="evenodd"
                d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z">
              </path>
            </svg>
          </button>
          <a href="https://flowbite.com" class="flex ml-2 md:mr-24">
            <img class="object-cover h-12 w-30" src="{% static 'assets/DDTC-Logo.png' %}" alt="Example Image" />
          </a>
          <h1 class="font-bold text-white">
            WELCOME, {{ nama }}
            <span
              class="bg-blue-100 text-blue-800 font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300">
              {{ role }}
            </span>
          </h1>
        </div>
        <div class="flex items-center justify-end">
          {% if izin_berlaku_konsultan %}
          {% if izin_berlaku_konsultan <= 30 %} <span
            class="bg-red-100 text-red-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-red-900 dark:text-red-300">
            Masa Berlaku Konsultan {{ izin_berlaku_konsultan }} Hari Lagi </span>
            {% else %}
            <span
              class="bg-blue-100 text-blue-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300">
              Masa Berlaku Konsultan {{ izin_berlaku_konsultan }} Hari Lagi
            </span>
            {% endif %}
            {% else %}
            {% endif %}
            {% if izin_berlaku_attorney %}
            {% if izin_berlaku_attorney <= 45 %} <span
              class="bg-red-100 text-red-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-red-900 dark:text-red-300">
              Masa Berlaku Konsultan {{ izin_berlaku_konsultan }} Hari Lagi </span>
              {% else %}
              <span
                class="bg-blue-100 text-blue-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300">
                Masa Berlaku Attorney {{ izin_berlaku_attorney }} Hari Lagi
              </span>
              {% endif %}
              {% else %}
              {% endif %}
              {% if information %}
              <span
                class="bg-blue-100 text-blue-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300">
                {{ information }}
              </span>
              {% endif %}
        </div>
      </div>
    </div>
  </nav>

  <aside id="logo-sidebar"
    class="fixed top-0 left-0 z-40 w-64 h-screen pt-20 transition-transform -translate-x-full bg-cream border-r border-gray-200 sm:translate-x-0 dark:bg-gray-800 dark:border-gray-700"
    aria-label="Sidebar">
    <div class="h-full px-3 pb-4 overflow-y-auto bg-cream dark:bg-gray-800">
      <ul class="space-y-2 font-medium">
        <li>
          <a href="{% url 'dashboard:main' %}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-darkblue-700 hover:text-white dark:hover:bg-gray-700">
            <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M3 8v10a1 1 0 0 0 1 1h4v-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v5h4a1 1 0 0 0 1-1V8M1 10l9-9 9 9" />
            </svg>
            <span class="ml-3">Home</span>
          </a>
        </li>
        <li>

          {% if role == "Admin" %}
          <a href="{% url 'dashboard:admin-notification' %}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-darkblue-700 hover:text-white dark:hover:bg-gray-700">
            <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M5 5h9M5 9h5m8-8H2a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h4l3.5 4 3.5-4h5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1Z" />
            </svg>
            <span class="flex-1 ml-3 whitespace-nowrap">Notifications</span>
            <span
              class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full dark:bg-blue-900 dark:text-blue-300">
              {{ number_of_admin_notifications }}</span>
            {% else %}
            <a href="{% url 'dashboard:user-notification' %}"
              class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-darkblue-700 hover:text-white dark:hover:bg-gray-700">
              <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                viewBox="0 0 20 18">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M5 5h9M5 9h5m8-8H2a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h4l3.5 4 3.5-4h5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1Z" />
              </svg>
              <span class="flex-1 ml-3 whitespace-nowrap">Notifications</span>
              <span
                class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full dark:bg-blue-900 dark:text-blue-300">
                {{ number_of_notifications }}</span>
              {% endif %}
            </a>
        </li>
        <li>
          <a href="{% url 'dashboard:teams' %}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-darkblue-700 hover:text-white dark:hover:bg-gray-700">
            <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M4.333 6.764a3 3 0 1 1 3.141-5.023M2.5 16H1v-2a4 4 0 0 1 4-4m7.379-8.121a3 3 0 1 1 2.976 5M15 10a4 4 0 0 1 4 4v2h-1.761M13 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm-4 6h2a4 4 0 0 1 4 4v2H5v-2a4 4 0 0 1 4-4Z" />
            </svg>
            <span class="flex-1 ml-3 whitespace-nowrap">Teams</span>
          </a>
        </li>
        {% if role == 'Admin' %}
        <li>
          <a href="{% url 'dashboard:tambah-personel' %}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-darkblue-700 hover:text-white dark:hover:bg-gray-700">
            <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M13 8h6m-3 3V5m-6-.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0ZM5 11h3a4 4 0 0 1 4 4v2H1v-2a4 4 0 0 1 4-4Z" />
            </svg>
            <span class="flex-1 ml-3 whitespace-nowrap">Add Personel</span>
          </a>
        </li>
        {% else %} {% endif %}
        <li>
          <a href="{% url 'dashboard:edit-user' %}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-darkblue-700 hover:text-white dark:hover:bg-gray-700">
            <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M4.109 17H1v-2a4 4 0 0 1 4-4h.87M10 4.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm7.95 2.55a2 2 0 0 1 0 2.829l-6.364 6.364-3.536.707.707-3.536 6.364-6.364a2 2 0 0 1 2.829 0Z" />
            </svg>
            <span class="flex-1 ml-3 whitespace-nowrap">Personal Information</span>
          </a>
        </li>
        <li>
          <a href="{% url 'project:projects' %}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-darkblue-700 hover:text-white dark:hover:bg-gray-700">
            <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M18 5h1v12a2 2 0 0 1-2 2m0 0a2 2 0 0 1-2-2V2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v15a2 2 0 0 0 2 2h14ZM10 4h2m-2 3h2m-8 3h8m-8 3h8m-8 3h8M4 4h3v3H4V4Z" />
            </svg>
            <span class="flex-1 ml-3 whitespace-nowrap">Project</span>
          </a>
        </li>
        <li>
          <a href="{% url 'authentication:logout' %}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-darkblue-700 hover:text-white dark:hover:bg-gray-700">
            <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 15">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M1 7.5h11m0 0L8 3.786M12 7.5l-4 3.714M12 1h3c.53 0 1.04.196 1.414.544.375.348.586.82.586 1.313v9.286c0 .492-.21.965-.586 1.313A2.081 2.081 0 0 1 15 14h-3" />
            </svg>
            <span class="flex-1 ml-3 whitespace-nowrap">Sign Out</span>
          </a>
        </li>
      </ul>
    </div>
  </aside>
  <div class="p-4 sm:ml-64 mt-20">{% block content %} {% endblock %}</div>
</body>

</html>